### ISSUE TITLE
ExamplesExtractor fails on recipes/hcl/movecontenttofile

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-build-gradle-plugin#18]
https://docs.openrewrite.org/recipes/hcl/movecontenttofile

## Expected
Valid markdown, no mention of null\```

## Actual
![image](https://github.com/openrewrite/rewrite-build-gradle-plugin/assets/1027334/7b88be01-be65-426c-9b28-d30fc47181c4)

**Comment by kunli2** [comment]
Fixed. For this case, it's new file, so before should not be displayed.

**Comment by kunli2** [comment]
Has manually summited to `rewrite-docs`, it takes some time to be updated on the web.

**Comment by timtebeek** [comment]
Thanks for the quick fix!
